target_image_size: 256
batch_size: 8
epochs: 4000
training_dataset_path: /data/raw_binarization_datasets/binarization_datasets/exp1/train
validation_dataset_path: /data/raw_binarization_datasets/binarization_datasets/exp1/val
dataset_repetition: 100
model_type: visual_attention_unet

# epochs calculation (from the segmenter paper)
# training_dataset_items = 2975
# total_steps = 80000*8//batch_size
# epochs = total_steps*batch_size//training_dataset_items
